name: chemalgprog
version: 0.1.0.0
<<<<<<< codex/reorganize-project-structure
synopsis: Chemical Algorithmic Programming
description: A library for molecular representation and probabilistic programming.
category: Development
author: Oliver Goldstein
maintainer: oliverjgoldstein@gmail.com, oliver.goldstein@cs.ox.ac.uk, sammarch2@gmail.com
license: AGPL-3.0
license-file: LICENSE.txt
extra-source-files:
  - CHANGELOG.md
  - README.md

=======
author: Oliver Goldstein
license: AGPL-3.0
>>>>>>> main
dependencies:
  - base >= 4.13 && < 4.21
  - monad-extras
  - transformers
  - mtl
  - deepseq
  - containers
  - ghc-heap
  - megaparsec >= 9.0 && < 10.0
  - vector
  - directory
  - filepath
  - bytestring
  - text
  - random
  - log-domain
  - statistics
  - array

library:
<<<<<<< codex/reorganize-project-structure
  source-dirs: src
=======
  source-dirs: .
>>>>>>> main
  exposed-modules:
    - LazyPPL
    - Molecule
    - Constants
    - Distr
    - Coordinate
    - Group
    - Orbital
    - Parser
    - Reaction
    - Serialisable
<<<<<<< codex/reorganize-project-structure
    - TestInference
  other-modules:
    - ExtraF
    - ParserSingle
    - LogPModel
    - Validator
=======
  default-language: Haskell2010
>>>>>>> main

executables:
  chemalgprog:
    main: Main.hs
    source-dirs: app
<<<<<<< codex/reorganize-project-structure
    dependencies:
      - chemalgprog
=======
    default-language: Haskell2010
>>>>>>> main
