name: chemalgprog
version: 0.1.0.0
synopsis: Chemical Algorithmic Programming
description: A library for molecular representation and probabilistic programming.
category: Development
author: Oliver Goldstein
maintainer: oliverjgoldstein@gmail.com, oliver.goldstein@cs.ox.ac.uk, sammarch2@gmail.com
license: AGPL-3.0-only
license-file: LICENSE
extra-source-files:
  - CHANGELOG.md
  - README.md
dependencies:
  - base >= 4.13 && < 4.21
  - monad-extras
  - transformers
  - mtl
  - deepseq
  - containers
  - ghc-heap
  - megaparsec >= 9.0 && < 10.0
  - vector
  - directory
  - filepath
  - bytestring
  - text
  - random
  - log-domain
  - statistics
  - array

library:
  source-dirs: src
  exposed-modules:
    - LazyPPL
    - Molecule
    - Constants
    - Distr
    - Coordinate
    - Group
    - Orbital
    - SlaterTypeOrbital
    - Parser
    - Reaction
    - Serialisable
    - TestInference
    - Benzene
  other-modules:
    - ExtraF
    - ParserSingle
    - LogPModel
    - Validator
  language: Haskell2010

executables:
  chemalgprog:
    main: Main.hs
    source-dirs: app
    dependencies:
      - chemalgprog
    language: Haskell2010
  parse-molecules:
    main: ParseMolecules.hs
    source-dirs: examples
    dependencies:
      - chemalgprog
    language: Haskell2010
